name: Bug Report
description: >
  Request form for general bugs. 
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: >
        Summary:
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: >
        Expected behavior:
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: >
        Actual behavior:
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: >
        Steps to reproduce:
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: >
        Version:
      placeholder: 0.1.1
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - 'Windows'
        - 'MacOs'
        - 'Linux distribution'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: >
        Logs:
      render: bash
      description: >
        Please provide the application logs.
    validations:
      required: true
  - type: textarea
    id: recording
    attributes:
      label: >
        Recording:
      description: >
        Please provide a recording of the bug if appropriate.