apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
- kind: ServiceAccount
  name: executor
---
apiVersion: v1
kind: Secret
metadata: 
  name: ninja-secret
stringData:
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forge-bucket
data:
  default: |
    s3:
      bucket: zetaforge
      endpoint: weed:8333
      region: us-east-1
      insecure: true
      accessKeySecret:
        name: ninja-secret
        key: accessKey
      secretKeySecret:
        name: ninja-secret
        key: secretKey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweed-config
data:
  config.json: |-
    {
      "identities": [
        {
          "name": "main",
          "credentials": [
            {
              "accessKey": "AKIAIOSFODNN7EXAMPLE",
              "secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
            }
          ],
          "actions": [
            "Read",
            "List",
            "Write"
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weed
  labels:
    app.kubernetes.io/name: weed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weed
    spec:
      containers:
        - name: weed
          image: chrislusf/seaweedfs
          command: ["weed", "server", "-s3.config=/home/config.json", "-s3"]
          ports:
            - containerPort: 8333
          volumeMounts:
            - name: config
              mountPath: /home
      volumes:
        - name: config
          configMap:
            name: seaweed-config
---
apiVersion: v1
kind: Service
metadata:
  name: weed
spec:
  type: LoadBalancer
  loadBalancerIP: ~
  selector:
    app.kubernetes.io/name: weed
  ports:
    - port: 8333
      targetPort: 8333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: registry
