// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package zdatabase

import (
	"database/sql"
)

type Execution struct {
	ID          int64
	Pipeline    int64
	Status      interface{}
	Created     int64
	Completed   sql.NullInt64
	Json        sql.NullString
	Deleted     int64
	Executionid string
	Workflow    sql.NullString
	Results     sql.NullString
}

type Pipeline struct {
	ID           int64
	Organization string
	Created      int64
	Uuid         string
	Hash         string
	Json         string
	Deployed     int64
	Deleted      int64
}

type SetupVersion struct {
	ID      int64
	Created int64
	Version string
}
