[project]
name = "zetaforge"
version = "0.3.3"
authors = [{ name = "zetane", email = "info@zetane.com" }]
description = "A Python package for interacting with Zetaforge pipelines"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: AGPL license",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.1",
    "yaspin>=2.1.0",
    "colorama>=0.4.4",
    "pytest>=7.4.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/zetaforge"]

[tool.pytest.ini_options]
addopts = "-v -s"
testpaths = ["tests"]

[project.urls]
"Homepage" = "https://github.com/zetane/ZetaForge"
"Bug Tracker" = "https://github.com/zetane/ZetaForge/issues"
