apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: default
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
- kind: ServiceAccount
  name: executor
---
apiVersion: v1
kind: Secret
metadata: 
  name: weed-secret
  namespace: default
stringData:
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forge-bucket
  namespace: default
data:
  default: |
    s3:
      bucket: zetaforge
      endpoint: weed:8333
      region: us-east-1
      insecure: true
      accessKeySecret:
        name: weed-secret
        key: accessKey
      secretKeySecret:
        name: weed-secret
        key: secretKey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweed-config
  namespace: default
data:
  config.json: |-
    {
      "identities": [
        {
          "name": "main",
          "credentials": [
            {
              "accessKey": "AKIAIOSFODNN7EXAMPLE",
              "secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
            }
          ],
          "actions": [
            "Read",
            "List",
            "Write"
          ]
        },
        {
          "name": "anonymous",
          "actions": [
            "Read",
            "List"
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weed
  namespace: default
  labels:
    app.kubernetes.io/name: weed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weed
    spec:
      containers:
        - name: weed
          image: chrislusf/seaweedfs
          command: ["weed", "server", "-s3.config=/home/config.json", "-s3"]
          ports:
            - containerPort: 8333
          volumeMounts:
            - name: config
              mountPath: /home
      volumes:
        - name: config
          configMap:
            name: seaweed-config
---
apiVersion: v1
kind: Service
metadata:
  name: weed
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: ~
  selector:
    app.kubernetes.io/name: weed
  ports:
    - port: 8333
      targetPort: 8333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
  labels:
    app.kubernetes.io/name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      containers:
        - name: registry
          image: registry:2.8.3
          ports:
            - containerPort: 5000
          env:
          - name: REGISTRY_STORAGE_DELETE_ENABLED
            value: "true"
          volumeMounts:
            - mountPath: /var/lib/registry
              name: host-mount
      volumes:
        - name: host-mount
          hostPath:
            path: /host/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
spec:
<<<<<<< HEAD
<<<<<<< HEAD
  type: LoadBalancer
  loadBalancerIP: ~
=======
>>>>>>> ae59fc7 (Switch to minikube)
=======
  type: LoadBalancer
  loadBalancerIP: ~
>>>>>>> 5e4bbba (Support Orbstack)
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app.kubernetes.io/name: registry