apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-aliases
  namespace: kube-system
  labels:
    kubernetes.io/minikube-addons: registry-aliases
    addonmanager.kubernetes.io/mode: Reconcile
data:
  registryAliases: >-
    example.org
    registry.minikube
  registrySvc: registry.kube-system.svc.cluster.local
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-aliases-hosts-update
  namespace: kube-system
  labels:
    kubernetes.io/minikube-addons: registry-aliases
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: registry-aliases-hosts-update
  template:
    metadata:
      labels:
        app: registry-aliases-hosts-update
    spec:
      initContainers:
        - name: update
          image: alpine:3.11
          volumeMounts:
            - name: etchosts
              mountPath: /host-etc/hosts
              readOnly: false
          env:
            - name: REGISTRY_ALIASES
              valueFrom:
                configMapKeyRef:
                  name: registry-aliases
                  key: registryAliases
          command:
            - sh
            - -ce
            - |
              NL=$'\n'
              TAB=$'\t'
              HOSTS="$(cat /host-etc/hosts)"
              [ -z "$REGISTRY_SERVICE_HOST" ] && echo "Failed to get hosts entry for default registry" && exit 1;
              for H in $REGISTRY_ALIASES; do                
                echo "$HOSTS" | grep "$H"  || HOSTS="$HOSTS$NL$REGISTRY_SERVICE_HOST$TAB$H";
              done;
              echo "$HOSTS" | diff -U 3 /host-etc/hosts - || echo "$HOSTS" > /host-etc/hosts
              echo "Done."
      containers:
        - name: pause-for-update
          image: gcr.io/google_containers/pause-amd64:3.1
      terminationGracePeriodSeconds: 30
      volumes:
        - name: etchosts
          hostPath:
            path: /etc/hosts
---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: registry-aliases-sa
   namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-aliases-crb
subjects:
- kind: ServiceAccount
  name: registry-aliases-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-aliases-patch-core-dns
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry-aliases-patch-core-dns
    spec:
      serviceAccountName: registry-aliases-sa
      volumes:
       - name: minikube
         hostPath: 
           path: /var/lib/minikube/binaries
      containers:
       - name: core-dns-patcher
         image: quay.io/rhdevelopers/core-dns-patcher
         imagePullPolicy: IfNotPresent
         volumeMounts:
           - mountPath: /var/lib/minikube/binaries
             name: minikube
             readOnly: true
      restartPolicy: Never
  backoffLimit: 4